- name: "Rust"
  hl_opts:
    numbers: true
    strings: true
    characters: true
    comments: true
    multiline_comments: true
    primary_keywords:
      - "as"
      - "break"
      - "const"
      - "continue"
      - "crate"
      - "else"
      - "enum"
      - "extern"
      - "false"
      - "fn"
      - "for"
      - "if"
      - "impl"
      - "in"
      - "let"
      - "loop"
      - "match"
      - "mod"
      - "move"
      - "mut"
      - "pub"
      - "ref"
      - "return"
      - "self"
      - "Self"
      - "static"
      - "struct"
      - "super"
      - "trait"
      - "true"
      - "type"
      - "unsafe"
      - "use"
      - "where"
      - "while"
      - "dyn"
      - "abstract"
      - "become"
      - "box"
      - "do"
      - "final"
      - "macro"
      - "override"
      - "priv"
      - "typeof"
      - "unsized"
      - "virtual"
      - "yield"
      - "async"
      - "await"
      - "try"
    secondary_keywords:
      - "bool"
      - "char"
      - "i8"
      - "i16"
      - "i32"
      - "i64"
      - "isize"
      - "u8"
      - "u16"
      - "u32"
      - "u64"
      - "usize"
      - "f32"
      - "f64"

- name: "JavaScript"
  hl_opts:
    numbers: true
    strings: true
    characters: true
    comments: true
    multiline_comments: true
    primary_keywords:
      - "if"
      - "else"
      - "for"
      - "while"
      - "do"
      - "switch"
      - "case"
      - "break"
      - "continue"
      - "return"
      - "function"
      - "var"
      - "let"
      - "const"
      - "try"
      - "catch"
      - "finally"
      - "throw"
      - "class"
      - "extends"
      - "super"
      - "import"
      - "export"
      - "default"
      - "async"
      - "await"
      - "instanceof"
      - "typeof"
      - "delete"
      - "in"
      - "with"
      - "new"
      - "this"
      - "true"
      - "false"
      - "Infinity"
      - "void"
      - "debugger"
      - "arguments"
    secondary_keywords:
      - "boolean"
      - "Number"
      - "NaN"
      - "String"
      - "undefined"
      - "null"
      - "Object"
      - "Symbol"
      - "BigInt"
      - "Array"
      - "Function"
      - "Map"
      - "Set"
      - "Promise"
      - "RegExp"
      - "Error"
      - "Date"
