name: rusty

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: rusty
    - name: Build
      run: |
          cd rusty  # Navigate to the directory containing Cargo.toml
          cargo build --verbose
